# yaml file for configuration of the neural sequence decoder  

base:
  date: ???
  exp_name: ???
  exp_dir: ???
  output_dir: './output'
  model_name: 'gru'
  log_file: 'log.txt'
  note: "char_10layers_1024units"
  config_file: 'exp_config.yaml'

# Data prep configs
dataset:
  raw_path: './data/competitionData'
  preprocessed_path: './data/preprocessed_char.pkl'

# Model
model:
  seqLen: 150
  maxTimeSeriesLen: 1200 
  lrStart: 0.02
  lrEnd: 0.02
  nUnits: 1024
  nLayers: 10
  nClasses: 29
  nInputFeatures: 256
  dropout: 0.4
  whiteNoiseSD: 0.8
  constantOffsetSD: 0.2
  gaussianSmoothWidth: 2.0
  strideLen: 4
  kernelLen: 32
  bidirectional: true
  l2_decay: 0.00001
  tokenizer: "char"
  tokenizer_path: None
  

# trainer
trainer:
  seed: 42
  batch_size: 16
  ml_logging: "wandb"
  project_name: 'speechbci'
  max_epochs: 100
  gpus: 1
  num_nodes: 1
  strategy: "ddp_find_unused_parameters_true"
  precision: "16-mixed"

# Configure environment variables for multi nodes multi GPU DDP
cluster: 
  nodes: 1
  node_rank: 0
  world_size: 1
  master_port: 1234
  master_addr: 'einstein'