name: Build Docker Container

on:
  push:
    branches:
      - main
      - master

jobs:
  docker-build-core:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push (core)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:docker"
          push: true
          tags: innerspeech/innerspeech-core:latest, innerspeech/innerspeech-core:${{ github.sha }}
